### ISSUE TITLE
Request:

### ISSUE THREAD

**Issue by FinderProcess** [Frankyfunkz/FrankyModMenu#1]
Spawning enemies and infinite logs if possible?

**Comment by Frankyfunkz** [comment]
Spawning enemies is already available by default using the console command "addcharacter name"
https://tonihub.com/characters/

Infinite logs is the same by using console command "loghack on"

**Comment by Frankyfunkz** [comment]
I have decided to add this anyway, thanks for your suggestion.
It is now included in the 0.9.6 update under the name Infinite Build Items
